### ISSUE TITLE
"key values mismatch"

### ISSUE THREAD

**Issue by aalrikabi** [cuongquay/node-red-contrib-aws-iot#18]
## I Am having the same problem using iont-node-red-contrib-aws-iot-hub 0.1.18 

here is node-red.log 
### 
14 Feb 18:17:17 - [info] [aws-iot-device:ali_thing] Attempt to connect to broker with ali_thing from: /home/dev/.node-red/certs
14 Feb 18:17:17 - [info] [aws-iot-device:ali_thing] Using the certificates that are presented as follows:
14 Feb 18:17:17 - [info] [aws-iot-device:ali_thing]  - keyPath   : /home/dev/.node-red/certs/ali_thing.private.key
14 Feb 18:17:17 - [info] [aws-iot-device:ali_thing]  - certPath  : /home/dev/.node-red/certs/ali_thing.cert.pem
14 Feb 18:17:17 - [info] [aws-iot-device:ali_thing]  - caPath    : /home/dev/.node-red/certs/root-CA.crt
14 Feb 18:17:17 - [error] [aws-mqtt out:3a2db45b.11c8bc] **Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch**
    at Error (native)
    at Object.createSecureContext (_tls_common.js:90:19)
    at Object.exports.connect (_tls_wrap.js:1001:48)
    at Object.buildBuilder [as mqtts] (/home/dev/.node-red/node_modules/aws-iot-device-sdk/device/lib/tls.js:26:21)
    at MqttClient._wrapper [as streamBuilder] (/home/dev/.node-red/node_modules/aws-iot-device-sdk/device/index.js:506:41)
    at MqttClient._setupStream (/home/dev/.node-red/node_modules/mqtt/lib/client.js:217:22)
    at new MqttClient (/home/dev/.node-red/node_modules/mqtt/lib/client.js:198:8)
    at new DeviceClient (/home/dev/.node-red/node_modules/aws-iot-device-sdk/device/index.js:509:19)
    at Object.DeviceClient [as device] (/home/dev/.node-red/node_modules/aws-iot-device-sdk/device/index.js:164:14)
    at awsNodeBroker.connect (/home/dev/.node-red/node_modules/iont-node-red-contrib-aws-iot-hub/aws-iot.js:50:50)
    at awsMqttNodeOut.<anonymous> (/home/dev/.node-red/node_modules/iont-node-red-contrib-aws-iot-hub/aws-iot.js:166:17)
    at emitOne (events.js:96:13)
    at awsMqttNodeOut.emit (events.js:188:7)
    at awsMqttNodeOut.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at InjectNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at InjectNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/20-inject.js:77:22)

I tested the script with node red mqtt node, and it was publishing to AWS with no problem. 
But using aws-iot node, i get this issue "key values mismatch". 

did i forget to make changes in AWS iot dashboard setting?
here is the AWS IOT policy:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}

**Comment by aalrikabi** [comment]
update:
I updated the policy and added multiple Actions and it worked for node-red mqtt node, publish and subscribe;

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Receive",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:UpdateThingShadow",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:GetThingShadow",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}

still node-red-contrib-aws-iot node is not working
