### ISSUE TITLE
Crash: TypeError: Cannot read property 'awsIot' of undefined

### ISSUE THREAD

**Issue by vielmetti** [cuongquay/node-red-contrib-aws-iot#6]
Not certain if I did something wrong in the config setup, but I did get this crash just now.

```
7 Oct 19:23:17 - TypeError: Cannot read property 'awsIot' of undefined
    at /usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/aws-iot.js:91:10
    at DeviceClient.<anonymous> (/usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/aws-iot.js:48:7)
    at emitNone (events.js:67:13)
    at DeviceClient.emit (events.js:166:7)
    at MqttClient.<anonymous> (/usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/node_modules/aws-iot-device-sdk/device/index.js:618:12)
    at emitOne (events.js:82:20)
    at MqttClient.emit (events.js:169:7)
    at MqttClient._handleConnack (/usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:696:10)
    at MqttClient._handlePacket (/usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:283:12)
    at process (/usr/src/node-red/node_modules/node-red-contrib-aws-iot-hub/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:227:12)
```

**Comment by cuongquay** [comment]
Better move the checking null pointer into the input block. I have just fixed it.

**Comment by cuongquay** [comment]
Changing the way to node-in for faster performance

**Comment by vielmetti** [comment]
Working now, thanks!
